### ISSUE TITLE
Mejorar mantenimiento y cobertura en el paquete Controller

### ISSUE THREAD

**Issue by Lizardo-Castillo** [Lizardo-Castillo/Proyecto_Backend#1]
Se debe modificar el archivo UserController.java para mejorar su mantenimiento y cobertura de pruebas. Esto incluye refactorizar el código y agregar pruebas unitarias donde no hay cobertura.

**Comment by KarlaCornejo** [comment]
Se añadio la covertura para el paquete de Controller en el archivo UserController.java. Tambien se modifico el mismo archivo para sea clean code. La covertura mejoro hasta un 70.9%.
