### ISSUE TITLE
Agregar cobertura la paquete Entity

### ISSUE THREAD

**Issue by Lizardo-Castillo** [Lizardo-Castillo/Proyecto_Backend#2]
El archivo User.java dentro del paquete de Entity carece de cobertura de pruebas. Se requiere añadir pruebas unitarias para asegurar su correcto funcionamiento.

**Comment by pieroadrianoCV** [comment]
Se añadio covertura para el paquete de Entity, en el archivo UserTest. La covertura mejoro hasta un 33.3%. Link : https://github.com/Lizardo-Castillo/Proyecto_Backend/commit/8beeb2f54911ad5261cd379ead42779fc69ea965
